# for more information about this YML file - refer to our infosec docs: https://github.com/fastfishio/infosec-docs/blob/main/scanners/secrets-scanner.md

name: Gitrack Secrets 

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

permissions:
  contents: read
  pull-requests: write
  
jobs:
  secrets-scanner:
    if: github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      READ_REPOS: ${{ secrets.SECURITY_READ_REPOS_TOKEN }}
      REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_CTX: ${{ toJson(github) }}

    steps:
    - uses: actions/checkout@master
    - name: Setup Gitrack Secrets
      id: setup-gitrack
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-ops-7b6b3e6fd90e6/gitrack-secrets-643595a/scripts/setup.sh | bash -

    - name: Running Gitrack Secrets (Secrets Scanning)
      id: running-gitrack
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-ops-7b6b3e6fd90e6/gitrack-secrets-643595a/scripts/scan.sh | bash -

    - name: Repository Cleanup Process
      id: repo-cleanup
      continue-on-error: true
      if: ${{ failure() && github.event_name == 'pull_request' && github.event.action == 'opened' }}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-ops-7b6b3e6fd90e6/gitrack-secrets-643595a/scripts/cleanup-process.sh | bash -

    - name: Safety Checks
      id: safety-checks
      continue-on-error: true
      if: ${{ failure() && github.event.pull_request.merged == true && github.event_name == 'pull_request' && github.event.action == 'closed'}}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-ops-7b6b3e6fd90e6/gitrack-secrets-643595a/scripts/safety-check.sh | bash -

    - name: Security Reporting and Monitoring
      id: reporting-monitoring
      continue-on-error: true
      if: ${{ failure() }}
      env:     
        STEPS_CTX: ${{ toJson(steps) }}
      run: |
        curl -sfL https://storage.googleapis.com/noon-security-ops-7b6b3e6fd90e6/gitrack-secrets-643595a/scripts/reporting-monitoring.sh | bash -

